FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements-pipelines.txt ./
RUN pip install --no-cache-dir -r requirements-pipelines.txt

COPY . .

RUN mkdir -p /app/data/bronze /app/data/silver /app/data/gold /app/logs/jobs

CMD ["sleep", "infinity"]
