newton: Newton Bernardi
juliano: Juliano Heyse
valdir: Valdir Noll
moises: Moisés Oliveira
dayan: Dayan Barbosa
fabiano: Fabiano Lima
saulo: Saulo Amaral
wesley: Wesley Knochenhauer
jaercio: Jaercio Chagas
alberto: Alberto Costa
rafael: Rafael Bastos
franklin: Franklin Ferreira